import '../agents/gemini.dart';


class CharacterEvaluationResult {
  final double score;
  final String feedback;

  CharacterEvaluationResult({required this.score, required this.feedback});
}

class CharacterEvaluator {
  final Gemini _gemini = Gemini();

  Future<CharacterEvaluationResult> evaluate({
    required String question,
    required String character,
  }) async {
    final prompt = '''
You are an expert in persona writing.

The following question was generated by an AI tutor:
"$question"

Evaluate how well this question matches the speaking style and personality of "$character".

Give a score from 0 to 1 (in 0.1 increments), and one sentence of feedback to improve the tone.

Format:
Score: <score>
Feedback: <feedback>
''';

    final response = await _gemini.sendPrompt(prompt);

    final scoreRegex = RegExp(r'Score:\s*(\d(?:\.\d)?)');
    final feedbackRegex = RegExp(r'Feedback:\s*(.*)');

    final score = scoreRegex.firstMatch(response)?.group(1);
    final feedback = feedbackRegex.firstMatch(response)?.group(1);

    return CharacterEvaluationResult(
      score: double.tryParse(score ?? '0.0') ?? 0.0,
      feedback: feedback ?? 'No feedback found.',
    );
  }
}
