// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYNKBEtSKCxowrtEMWGyM9nf9P98xV6rI',
    appId: '1:879807719500:web:9e84e7274baed04e67ece9',
    messagingSenderId: '879807719500',
    projectId: 'situation-coach',
    authDomain: 'situation-coach.firebaseapp.com',
    storageBucket: 'situation-coach.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4__7rXHyeyW3cUsiCGu0DvhwAPCjxNc4',
    appId: '1:879807719500:android:5cf921e9a2fef47167ece9',
    messagingSenderId: '879807719500',
    projectId: 'situation-coach',
    storageBucket: 'situation-coach.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSod6vk9FK2Atn28GPPlgG60_UoHFp_dQ',
    appId: '1:879807719500:ios:264875783c69c71d67ece9',
    messagingSenderId: '879807719500',
    projectId: 'situation-coach',
    storageBucket: 'situation-coach.firebasestorage.app',
    iosBundleId: 'com.example.situation_coach',
  );
}
